-- Actualizar tabla usuarios para agregar campos de logos y firma
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS logo_izquierdo VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS logo_derecho VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS nombre_firma VARCHAR(200) DEFAULT 'EDINSON PAUL GAMONAL VIDARTE',
ADD COLUMN IF NOT EXISTS cargo_firma VARCHAR(200) DEFAULT 'TESORERO DNI';

